=begin
#Catalog API

#This API gets and orders catalog items from different cloud sources.

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for CatalogApiClient::IconApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IconApi' do
  before do
    # run before each test
    @instance = CatalogApiClient::IconApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IconApi' do
    it 'should create an instance of IconApi' do
      expect(@instance).to be_instance_of(CatalogApiClient::IconApi)
    end
  end

  # unit tests for destroy_icon
  # Delete an existing Icon
  # Deletes the icon based on the icon ID passed
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'destroy_icon test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for icons_id_get
  # Fetch an Icon by ID
  # Fetch an Icon by ID
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [Icon]
  describe 'icons_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for icons_post
  # Create an Icon
  # Creates an Icon from the specified parameters
  # @param [Hash] opts the optional parameters
  # @option opts [File] :content 
  # @return [Icon]
  describe 'icons_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_icon_data
  # Fetches the specified icon&#39;s image
  # Fetch the specified portfolio item&#39;s icon image.
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'show_icon_data test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_icon
  # Edit an existing Icon
  # Edits Icon specified by the given ID.
  # @param id ID of the resource
  # @param icon Parameters needed to update an Icon
  # @param [Hash] opts the optional parameters
  # @return [Icon]
  describe 'update_icon test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
