=begin
#Catalog API

#This API gets and orders catalog items from different cloud sources.

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for CatalogApiClient::OrderItemApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrderItemApi' do
  before do
    # run before each test
    @instance = CatalogApiClient::OrderItemApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrderItemApi' do
    it 'should create an instance of OrderItemApi' do
      expect(@instance).to be_instance_of(CatalogApiClient::OrderItemApi)
    end
  end

  # unit tests for list_approval_requests
  # Gets a list of approval requests for an item
  # Gets a list of approval request associated with an order item. As the item is being approved one can check the status of the approvals. 
  # @param order_item_id The Order Item ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @return [ApprovalRequestsCollection]
  describe 'list_approval_requests test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_progress_messages
  # Gets a list of progress messages in an item
  # Gets a list of progress messages associated with an order item. As the item is being processed the provider can update the progress messages. 
  # @param order_item_id The Order Item ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @return [ProgressMessagesCollection]
  describe 'list_progress_messages test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
