=begin
#Catalog API

#This API gets and orders catalog items from different cloud sources.

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CatalogApiClient::TenantSettingsSchema
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TenantSettingsSchema' do
  before do
    # run before each test
    @instance = CatalogApiClient::TenantSettingsSchema.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TenantSettingsSchema' do
    it 'should create an instance of TenantSettingsSchema' do
      expect(@instance).to be_instance_of(CatalogApiClient::TenantSettingsSchema)
    end
  end
end
